version: 2
jobs:
  build:
    branches:
      only:
        - master
      ignore:
        - develop
    docker:
      - image: 'circleci/node:16'
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: 'npm install'
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run:
          name: 'Build Project'
          command: 'npm run e2e'   